-- 01
-- [Char]
-- (Char,Char,Char)
-- [(Bool,Char)]
-- ([Bool],[Char])
-- [[a] -> [a]] # olha a pegadinha aew

-- 02
-- [a] -> a
-- (a,b) -> (b,a)
-- a -> b -> (a,b)
-- Num a -> a -> a
-- Eq a => [a]-> Bool
-- (a -> a) -> a -> a # Porque?
